name: Setup, Build
on: [push, workflow_dispatch]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: actions/checkout@v4
      - name: check latest release tag of Moddable
        run: |
          API_URL="https://api.github.com/repos/Moddable-OpenSource/moddable/releases"
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $API_URL)
          LATEST_TAG_NAME=$(echo $RESPONSE | jq -r '.[0].tag_name')
          LATEST_TAG_ID=$(echo $RESPONSE | jq -r '.[0].id')
          echo "Latest release tag_name of Moddable: $LATEST_TAG_NAME (id:$LATEST_TAG_ID)"
          echo "latest_tag_id=$LATEST_TAG_ID" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
        working-directory: ./moddable
        shell: bash
      - name : echo cache key
        run: echo "${{ runner.os }}-dependencies-${{ env.latest_tag_id }}"
      - name: Restore cached dependencies of Moddale and ESP-IDF
        id: cache-dependencies-restore
        uses: actions/cache/restore@v4
        with:
          path: |
             $HOME/.local/share
             $HOME/.espressif
          key: ${{ runner.os }}-dependencies-${{ env.latest_tag_id }}
      - name: install Moddable
        if: steps.cache-dependencies-restore.outputs.cache-hit != 'true'
        run: npm run setup:moddable
        working-directory: ./moddable
        shell: bash
      - name: install ESP32
        if: steps.cache-dependencies-restore.outputs.cache-hit != 'true'
        run: source $HOME/.local/share/xs-dev-export.sh && npm run setup:esp32
        working-directory: ./moddable
        shell: bash
      - name: Save dependencies of Moddale and ESP-IDF to cache
        id: cache-dependencies-save
        uses: actions/cache/save@v4
        with:
          path: |
             $HOME/.local/share
             $HOME/.espressif
          key: ${{ runner.os }}-dependencies-${{ env.latest_tag_id }}
      - name: xs-dev doctor
        run: source $HOME/.local/share/xs-dev-export.sh && npm run doctor
        working-directory: ./moddable
        shell: bash
      - name: Measurement of cache target size.
        run: du -sh $HOME/.local/share && du -sh $HOME/.espressif/ 
        shell: bash
      - name: build balls example app for ESP32.
        run: source $HOME/.local/share/xs-dev-export.sh && mcconfig -d -m -p esp32/m5stack $HOME/.local/share/moddable/examples/piu/balls/manifest.json -t build
        shell: bash

